### ISSUE TITLE
Breathe stacktraces if using auto-directives and doxygen isn't on the system 

### ISSUE THREAD

**Issue by michaeljones** [breathe-doc/breathe#121]
The Popen call in the subprocess module fails in a ugly way. We should test if `doxygen` is present before proceeding.

**Comment by melvinvermeeren** [comment]
@michaeljones #122 had a similar ugly message in the past. I don't have anything available locally to do a quick test of this.

Do you perhaps know the message printed or where it would fail? Thanks.

**Comment by michaeljones** [comment]
Closing due to sheer age. I'm sure there will be motivation to re-open or re-create if it is an issue.
