### ISSUE TITLE
Every doxygengroup has a dependency on every XML file in the project

### ISSUE THREAD

**Issue by marc-h38** [breathe-doc/breathe#420]
.. which means **all** .rst files with any sort of doxygengroup get rebuilt even when just one character changes in **one** XML file.

This makes incremental builds almost as slow as building from scratch.

I traced the issue to the method DoxygenTypeSubItemFinder(ItemFinder).filter_():
https://github.com/michaeljones/breathe/blob/v4.11.1/breathe/finder/index.py

```
class DoxygenTypeSubItemFinder(ItemFinder):
    def filter_(self, ancestors, filter_, matches):
        """Find nodes which match the filter. Doesn't test this node, only its children"""

        compounds = self.data_object.get_compound()
        node_stack = stack(self.data_object, ancestors)

        for compound in compounds:
            compound_finder = self.item_finder_factory.create_finder(compound)
            compound_finder.filter_(node_stack, filter_, matches)
```

When this runs, "compounds" is _already_ a list of _all_ XML files in the project, no matter which actual `doxygengroup` they are. Then for every XML file compound, compound_finder.filter_() calls [FileStateCache.update() ](
https://github.com/michaeljones/breathe/blob/v4.11.1/breathe/directives.py#L714) which adds one by one the current .rst doxygengroup to the compound->docnames list of .rst dependents - for every .xml compound.

Unlike dependency tracking, the filtering itself seems OK because the list of `matches` has only one matching XML compound at the end of the loop. The "everything to everything" spurious dependencies get added anyway.

One of these two things is wrong and I need to know which one to investigate further:
- either `compounds` should not be a list of **all** XML files in the project before the loop. Then what should it be at this point?
- or the `doxygengroup` should be added to the docnames list of dependents of the XML compound **only if** there's a match and not unconditionally

Which one is wrong?

**Comment by marc-h38** [comment]
@michaeljones , @melvinvermeeren , any chance you could quickly answer the final A/B question? without spending too much time looking at all the implementation details.

**Comment by melvinvermeeren** [comment]
I am afraid that I don't know and the chance is high Michael doesn't either since it has been years since most of the complexity of Breathe was written. The best thing to do is probably hack one of the A/B quickly and see how the behaviour changes to figure out if it is A or B.
