### ISSUE TITLE
Can doxygengroup list functions in the alphabetical order of function names

### ISSUE THREAD

**Issue by chncwang** [breathe-doc/breathe#701]
I have tens of functions from the same group but they are scattered in several C++ header files. When I introduce them in the rst file, I want to list them in the alphabetical order of function names. Would you mind telling me how to do this? Many thanks!

**Comment by vermeeren** [comment]
@chncwang You wish to use `.. doxygengroup::` directive and have the resulting output sorted, correct?

**Comment by schlatterbeck** [comment]
I have the same issue (in C not C++). I'm using exhale to create the breathe input. This creates one file for each function in a group like:

first file:
```
.. _exhale_function_group__allele_1ga0416d60b1b35167e549125a549df0cf0:

Function PGAEncodeRealAsGrayCode
================================

- Defined in :ref:`file_source_evaluate.c`


Function Documentation
----------------------


.. doxygenfunction:: PGAEncodeRealAsGrayCode(PGAContext *, int, int, int, int, double, double, double)
   :project: PGAPack

```
second file:
```
.. _exhale_function_group__allele_1ga151112fd7f454eed5f654a02fcecbb24:

Function PGASetBinaryAllele
===========================

- Defined in :ref:`file_source_binary.c`


Function Documentation
----------------------


.. doxygenfunction:: PGASetBinaryAllele(PGAContext *, int, int, int, int)
   :project: PGAPack

```

third file:
```
.. _exhale_function_group__allele_1ga21db49cb4c109f30ee276646eeb5ddee:

Function PGAGetIntegerFromBinary
================================

- Defined in :ref:`file_source_evaluate.c`


Function Documentation
----------------------


.. doxygenfunction:: PGAGetIntegerFromBinary(PGAContext *, int, int, int, int)
   :project: PGAPack

```
See how the names exhale creates for these are not in alphabetical order of the function names. Exhale uses the doxygen handles which also do not reflect the function name order. The functions in the group end up in this arbitrary order doxygen happens to extract them. Note that I did not find a way to ask doxygen to order the contents of a group either.

Note that I'm using doxygen's \ingroup directive scattered through several input files. So these functions *are* in arbitrary order to begin with...

**Comment by schlatterbeck** [comment]
I just noticed that the generated sequence also does not follow the doxygen handle sequence. Instead it seems to order by filename and position in file.

This is the generated sequence, I'm giving the handle after the name. The filenames of the .rst files are 
function_group__allele_<handle>.
```
void PGASetBinaryAllele
int PGAGetBinaryAllele
void PGASetCharacterAllele
char PGAGetCharacterAllele
double PGAGetRealFromBinary
double PGAGetRealFromGrayCode
void PGAEncodeRealAsBinary
void PGAEncodeRealAsGrayCode
```

The first two are in `binary.c`, 3+4 in `char.c`, ...
