### ISSUE TITLE
Doxygenclass not recognizing Python package class

### ISSUE THREAD

**Issue by changliao1025** [breathe-doc/breathe#886]
I am trying to use the doxygenclass for several python classes:

I have tried 

    .. doxygenclass:: pyflowline::pybasin

and

    .. doxygenclass:: pybasin

pyflowline is the Python package name, also the project name.
pybasin is a class within pyflowline

And I received errors like this after rtd build:

doxygenclass: Cannot find class “pyflowline::pybasin” in doxygen xml output for project “pyflowline” from directory: ../_build/xml

doxygenclass: Cannot find class “pybasin” in doxygen xml output for project “pyflowline” from directory: ../_build/xml

The repository is at: https://github.com/changliao1025/pyflowline
and the rst is located at: 
https://github.com/changliao1025/pyflowline/blob/main/docs/source/api/api.rst

Most examples I found are for C++, not for Python.

If I use

    .. doxygenindex::

It works, but it includes everything from the XML index.
So my question, how to use the directives for a pure Python package? None the existing examples are for Python as well.

**Comment by michaeljones** [comment]
Hi, Sphinx supports python natively. You shouldn't need Breathe for it. Have you tried checking the Sphinx docs? Or is there a specific reason to use Breathe for this?

**Comment by changliao1025** [comment]
I am aware of that. But I used doxygen for a C++ project and found some features such as call graph quite useful. So I decided to keep using it for Python. (I haven't tested the differences yet.)

I just ran the doxygen locally and checked the XML files. It seems Doxygen generates Python class differently.
The following method worked for my question:

    .. doxygenclass:: pyflowline::classes::basin::pybasin
        :members:

It would be interesting to know how the sphinx compared to doxygen results, though. Thanks.

**Comment by michaeljones** [comment]
Thanks for explaining. We're struggling to find the resources to do significant work on Breathe at the moment but it is interesting to know that fully supporting Doxygen's Python output might provide some features that Sphinx struggles to provide natively.
