### ISSUE TITLE
Documentation in wrong locations when using doxygenfile or autodoxygenfile

### ISSUE THREAD

**Issue by ReenigneArcher** [breathe-doc/breathe#900]
Firstly, I am pretty new to breathe and doxygen, so it's very possible I'm just doing something wrong.

I will attempt to simplify this as much as possible. The problem I am facing is that some files have the documentation moved to another file. I'm sure this is because I'm importing the header into my `main.cpp` file.

## First Attempt
conf.py
```py
breathe_default_project = 'src'
breathe_implementation_filename_extensions = ['.c', '.cc', '.cpp', '.mm']
breathe_order_parameters_first = False
breathe_projects = dict(
    src="../build/doxyxml"
)

subprocess.run('doxygen', shell=True, cwd=source_dir)
```

main.rst
```rst
main
====

.. doxygenfile:: main.h
```

system_tray.rst
```rst
system_tray
===========

.. doxygenfile:: system_tray.h
```

## Second Attempt (with #896 or #899)
conf.py
```py
breathe_default_project = 'src'
breathe_implementation_filename_extensions = ['.c', '.cc', '.cpp', '.mm']
breathe_order_parameters_first = False
breathe_projects_source = {
    "src": (
        "../../src", [
            "main.cpp",
            "main.h",
        ]
    ),
    "system_tray": (
        "../../src", [
            "system_tray.cpp",
            "system_tray.h",
        ]
    ),
}
```

main.rst
```rst
main
====

.. autodoxygenfile:: main.h
   :project: src
```

system_tray.rst
```rst
system_tray
===========

.. autodoxygenfile:: system_tray.h
   :project: system_tray
```

Result in either case, is that everything from `system_tray.h` is actually documented in `main.rst` instead of `system_tray.rst`.

Live results:
https://docs.lizardbyte.dev/projects/sunshine/en/nightly/source/src/main.html
https://docs.lizardbyte.dev/projects/sunshine/en/nightly/source/src/system_tray.html

I would have expected separating the `system_tray` into a separate Doxygen project to give different results, since I wouldn't think it would have access to the other projects, but the result is the same.

I'm unsure if this is a configuration issue on my end, or a bug in breathe. I'm pretty new to breathe and Doxygen, but have used Sphinx quite a bit with Python projects. Normally there I use `automodule` and have never faced anything like this.

I'd be grateful if anyone can offer any guidance or workarounds.

**Comment by vermeeren** [comment]
@ReenigneArcher I do think the Breathe docs use `:project:` quite a lot in the tests/example docs. There is still of course a chance there are bugs specifically to this directive, but it might help you exclude configuration issues and the like.

If you `grep -rIin :project:` in the Breathe root there are a bunch, and the `documentation/source/conf.py` contains the list of all projects. Do note that this mostly uses `breathe_projects` and not the `_source` suffix variant.

Generally speaking I do highly recommend running Doxygen yourself for XML generation instead of letting Breathe invoke it for you, there are too many limitations/issues with it in my experience. From my point of view it's only kept around for backwards compatibility but should not really be used any longer.

I do note your PRs #896 and #899, so thanks a lot for trying to find the actual cause. I haven't checked too in-depth yet as I'm a bit short of time, but hopefully my thoughts help clarify things somewhat.

**Comment by ReenigneArcher** [comment]
So there were two things going on.

The first one, is obvious. I had the functions defined in the header of `main.h`... probably from before I moved everything to a separate header.

The second issue, is not as obvious to me. But the namespace was inside a macro, so this was either skipped by doxygen and/or breathe.

**does not document**
```cpp
#if defined SUNSHINE_TRAY && SUNSHINE_TRAY >= 1

namespace system_tray {
  // blah blah blah
}  // namespace system_tray
#endif
```

**does document**
```cpp
namespace system_tray {
  // blah blah blah
}  // namespace system_tray
```

I'm not sure if this is something I did wrong, or a bug with doxygen or breathe. I am not 100% sure about this, but I believe doxygen documents it, and breathe does not. I would expect documentation to appear for code whether it's within a macro or not.

**Comment by vermeeren** [comment]
@ReenigneArcher afaik Breathe reads the Doxygen XML as-is so it might have been omitted from XML. You could inspect XML manually to verify if it is there or not. I do remember doing this type of preprocessing myself some years ago.

Checking https://www.doxygen.nl/manual/preprocessing.html a bit, I remember setting what would you in your case something similar to:

```
ENABLE_PREPROCESSING = YES
MACRO_EXPANSION = YES
EXPAND_ONLY_PREDEF = YES
PREDEFINED = SUNSHINE_TRAY=1
```

I do remember there are quite some options in Doxygen and it can be very finicky with what ends up working and in which way, as the resulting XML can be quite different depending on how the preprocessing way done. Does experimenting a bit with your `Doxyfile` show anything useful?
