### ISSUE TITLE
Display function names in sidebar

### ISSUE THREAD

**Issue by cc00010** [breathe-doc/breathe#915]
`.. doxygenfile::` does not display function names in sidebar. But standard `.. function::` does.

`function` directive
<img width="227" alt="Screenshot 2023-05-14 at 11 45 09 PM" src="https://github.com/breathe-doc/breathe/assets/92562933/c49a46c9-ce95-40fe-adc2-0ff4ed77d093">

**Comment by cc00010** [comment]
No, I'm using `doxygenfile`. It seems like this is a sphinx issue. Because, when you do `.. function:: somefunc()` (aka `.. py:function:: somefunc()`) it works as expected. But when it's: `.. c:function:: void somefn(void);`, it does not show the function in the sidebar.

**Comment by vermeeren** [comment]
@cc00010 Might indeed be in Sphinx difference between C and C++ domain implementation, you could check those from here https://github.com/sphinx-doc/sphinx/tree/master/sphinx/domains. They are completely distinct implementations afaik.

**Comment by cc00010** [comment]
Yeah, thanks for the response @vermeeren. I wonder if there's a flag to turn on/off that thing.

**Comment by cc00010** [comment]
I'm trying to investigate it, but can't really find the thing I want

**Comment by cc00010** [comment]
Closing it. The issue is not related to this repository.
