### ISSUE TITLE
Sphinx 7.2 support

### ISSUE THREAD

**Issue by AA-Turner** [breathe-doc/breathe#943]
Hi,

This is a reference to https://github.com/sphinx-doc/sphinx/issues/11605, where a user has reported an incompatability in:

```python
        self._default_build_dir = os.path.dirname(app.doctreedir.rstrip(os.sep))
```

with the following reproducer:

```shell
$ echo "Test" > index.rst
$ echo "extensions = ['breathe']" > conf.py
$ sphinx-build -M html . _build
Running Sphinx v7.2.0

Exception occurred:
  File "/Users/simon/.local/share/virtualenvs/fob-HUh8Hd7H/lib/python3.11/site-packages/breathe/project.py", line 116, in __init__
    self._default_build_dir = os.path.dirname(app.doctreedir.rstrip(os.sep))
                                              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute 'rstrip'
The full traceback has been saved in /var/folders/x6/97fjm0c540s7yn9zlv7fp9k00000gn/T/sphinx-err-0d2v5eaa.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Sphinx 7.2 changed all internal paths to ``pathlib`` -- this could be resolved by either calling ``os.fspath`` on ``app.doctreedir`` or by calling ``Path(app.doctreedir).parent`` to also support pre-7.2 Sphinx.

A

**Comment by AA-Turner** [comment]
Note, I've released [Sphinx 7.2.3](https://pypi.org/project/Sphinx/7.2.3/) which contains a work-around for this issue. Projects are still **heavily encouraged** to use ``pathlib.Path`` objects over ``str`` based paths.

A

**Comment by mattip** [comment]
Thanks!

**Comment by mattip** [comment]
It would be helpful if breathe would reflect that requirement in its setup.py https://github.com/breathe-doc/breathe/blob/542ae9b9ed6e5bd5e92ba2360b094df8931ba756/setup.py#L20

**Comment by mattip** [comment]
Cool, thanks @AA-Turner for the fixes.

**Comment by AA-Turner** [comment]
Note tests are failing etc -- I spent a couple of hours last night just doing modernisation, more work still needed to get everything to green. 

I'm able to merge PRs if any are outstanding that you think ought be looked at.

A

**Comment by mattip** [comment]
I just want what we (NumPy) already have to work with a more modern sphinx. Although I admit sphinx is moving a little too fast for me, I would prefer they not break things.

**Comment by dylanh724** [comment]
```
lib\site-packages\breathe\project.py:116: RemovedInSphinx90Warning: Sphinx 9 will drop support for representing paths as strings. Use "pathlib.Path" or "os.fspath" instead.
  self._default_build_dir = os.path.dirname(app.doctreedir.rstrip(os.sep))
```
Hm, did we miss a spot?

**Comment by Lucas-C** [comment]
I'm also seeing this warning while using `breathe==4.35.0` & `sphinx==8.1.3`
