### ISSUE TITLE
Breathe breaks with sphinx 7.3.X

### ISSUE THREAD

**Issue by Chekov2k** [breathe-doc/breathe#981]
I raised an MR on sphinx to export the missing CPP ast classes breathe needs: https://github.com/sphinx-doc/sphinx/pull/12298
Not sure those are all that are required but I could generate documentation for my cpp code base

**Comment by hefl99** [comment]
Same Problem here:

Tried to installl latest breathe v4.35.0 on python 3.12, which installed sphinx v7.3.5

Fixes it temporarily by downgrading sphinx to v5.3.0 and numpydoc to v1.6.0.

This is mayor issue for upcoming releases of our project:

https://github.com/itom-project

**Comment by AA-Turner** [comment]
[Sphinx 7.3.6](https://pypi.org/project/Sphinx/7.3.6/) has been released with fixes.

A

**Comment by Chekov2k** [comment]
Can confirm that works for me ;-)
