### ISSUE TITLE
Sphinx 8 will drop support for representing paths as strings.

### ISSUE THREAD

**Issue by tuxfan** [breathe-doc/breathe#984]
Not sure if anyone is working on this. However, I'm getting `RemovedInSphinx80Warning` for line 116 in `project.py`.
https://github.com/breathe-doc/breathe/blob/542ae9b9ed6e5bd5e92ba2360b094df8931ba756/breathe/project.py#L116

**Comment by tomasbw** [comment]
https://github.com/breathe-doc/breathe/pull/977
